# Generated by Django 5.0.9 on 2024-11-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id_auditor', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(choices=[('Auditor', 'Auditor')], default='Auditor', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prueba.user')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('testing', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('nombre_control', models.CharField(max_length=100)),
                ('codigo_control', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Terminado', 'Terminado')], default='Pendiente', max_length=50)),
                ('ciclo', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='prueba.auditor')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('last_date', models.DateField()),
                ('nombre_prueba', models.CharField(max_length=100)),
                ('comentarios', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=50)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='prueba.control')),
            ],
        ),
        migrations.CreateModel(
            name='EncabezadoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recursos', models.TextField(blank=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encabezados', to='prueba.control')),
            ],
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='prueba.control')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explicacion', models.TextField()),
                ('validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='prueba.validacion')),
            ],
        ),
    ]
